apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vegeta-k8s.fullname" . }}
  labels:
    {{- include "vegeta-k8s.labels" . | nindent 4 }}
data:
  vegeta-targets.txt: |
    {{- range required "missing app.httpTargets" .Values.app.httpTargets }}
    {{ . }}
    {{- end }}
