apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "vegeta-k8s.fullname" . }}
  labels:
    {{- include "vegeta-k8s.labels" . | nindent 4 }}
spec:
  parallelism: {{ default "1" .Values.jobParallelism }}
  backoffLimit: 0
  template:
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "vegeta-k8s.serviceAccountName" . }}
      securityContext:
        sysctls:
          - name: net.ipv4.ip_local_port_range
            value: "1024 65535"
      restartPolicy: OnFailure
      volumes:
        - name: temp-volume
          emptyDir: {}
        - name: vegeta-targets
          configMap:
            name: {{ include "vegeta-k8s.fullname" . }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: job-name
                  operator: In
                  values:
                  - {{ include "vegeta-k8s.fullname" . }}
              topologyKey: kubernetes.io/hostname
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{- if .Values.image.tag -}}{{ .Values.image.tag }}{{- else -}}{{ .Chart.AppVersion }}{{- end -}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: temp-volume
              mountPath: /temp-dir
            - name: vegeta-targets
              mountPath: /opt/vegeta-targets.txt
              subPath: vegeta-targets.txt
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "vegeta-k8s.fullname" .) .Values.app.awsSecretName }}
                  key: access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "vegeta-k8s.fullname" .) .Values.app.awsSecretName }}
                  key: secret_access_key
            - name: AWS_DEFAULT_REGION
              value: "{{ required "missing app.awsDefaultRegion" .Values.app.awsDefaultRegion }}"
            - name: S3_BUCKET_NAME
              value: "{{ required "missing app.s3BucketName" .Values.app.s3BucketName }}"
            - name: TEMP_DIR
              value: /temp-dir
            - name: TARGETS
              value: /opt/vegeta-targets.txt
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DURATION
              value: "{{ required "missing app.duration" .Values.app.duration }}"
            - name: RATE
              value: "{{ required "missing app.rate" .Values.app.rate }}"
            {{- if .Values.app.keepalive }}
            - name: KEEPALIVE
              value: "{{ .Values.app.keepalive }}"
            {{- end }}
            {{- if .Values.app.maxWorkers }}
            - name: MAX_WORKERS
              value: "{{ .Values.app.maxWorkers }}"
            {{- end }}
            {{- if .Values.app.maxConnections }}
            - name: MAX_CONNECTIONS
              value: "{{ .Values.app.maxConnections }}"
            {{- end }}
            {{- if .Values.app.connections }}
            - name: CONNECTIONS
              value: "{{ .Values.app.connections }}"
            {{- end }}
            {{- if .Values.app.timeout }}
            - name: TIMEOUT
              value: "{{ .Values.app.timeout }}"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
